version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  
  ApplicationStart:
    - location: java -jar demo-0.0.1-SNAPSHOT.jar
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: ec2-user